# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7576cecbce048f21ab382ab58cfbc65b1346db0a49ee4a6813423caf874b389486edf43bbea30a5c2a59d3d4e0ba8cebf9a6af655f95137665de41b630160e6

test:
  secret_key_base: 6437bf634cba177fd973a50ebc7fe31fb6979e42c993548926946232a8ceb388c38e9da79836fdf05cabb0b6aa78ceb6f989e2162d11284a466c1cddaeed317d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  linkedin_key: <%= ENV["LINKEDIN_KEY"] %>
  linkedin_secret: <%= ENV["LINKEDIN_SECRET"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_secret: <%= ENV["GOOGLE_SECRET"] %>
